apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dobby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dobby
  template:
    metadata:
      name: dobby
      labels:
        app: dobby
    spec: 
      containers:
      - name: dobby
        image: thecasualcoder/dobby
        livenessProbe:
          httpGet:
            path: /health
            port: 4444
        readinessProbe:
          httpGet:
            path: /readiness
            port: 4444
