apiVersion: v1
kind: Pod
metadata:
  name: metadata-v2-1
  labels:
    app: metadata
spec:
  containers:
  - name: metadata
    image: sunitparekh/metadata:v2.0
    env:
    - name: MONGODB_URI
      value: mongodb://localhost/metadata
