apiVersion: batch/v1
kind: Job
metadata:
  name: pi-retry-with-2
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["bad-command"]
      restartPolicy: Never
  backoffLimit: 2
